### ISSUE TITLE
Don't commit cause .lintstagedrc in homework 1.

### ISSUE THREAD

**Issue by sylvestrevgen** [goitacademy/react-homework#1]
Don't commit cause .lintstagedrc - husky don't like "linters" string in .lintstagedrc. I just remove "linters" {} and leave pathes and it commits and works.

**Comment by luxplanjay** [comment]
I'm pretty sure this is not an issue with homework but with how lint-staged config changed after an update. So i'm closing this here and will take a look at course materials.
